# Generated by Django 4.0.4 on 2022-05-14 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_tast_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
